nelmio_api_doc:
    documentation:
        info:
            title: RESQ18 API Documentation
            description: An awesome app!
            version: 1.0.0
        tags:
            - name: 'Auth'
              description: 'Endpoints related to user authentication'
            - name: 'Profile'
              description: 'Endpoints related to user infos management'
            - name: 'Categories'
              description: 'Endpoints related to categories'
            - name: 'Questions'
              description: 'Endpoints related to questions'
            - name: 'User score'
              description: 'Endpoints related to user score'        
            - name: 'User'
              description: 'Endpoints related to user management'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc