version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:latest
    container_name: database_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailer_container
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1 
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:
