services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}  
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - "1025:1025"
      - "8025:8025"  
    networks:
      - app-network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1 
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  ###> PHP ###
  php:
    image: php:8.2-fpm
    container_name: php
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      -  ../back:/var/www/back

  ###> Server Nginx ###
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../back:/var/www/back
    depends_on:
      - php
    networks:
    - app-network

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:

networks:
  app-network:
    driver: bridge
