services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}  
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - "1025:1025"
      - "8025:8025"  
    networks:
      - app-network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1 
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: always

  ###> PHP ###
  php:
    build:
      context: ../back
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../back:/var/www/html
      - ./docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    depends_on:
      - database
      - mailer
    networks:
      - app-network
    environment:
      - DATABASE_URL=pgsql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - MAILER_DSN=smtp://mailer:1025

  ###> Server Nginx ###
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../back:/var/www/html
    depends_on:
      - php
    networks:
    - app-network
    restart: always

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:

networks:
  app-network:
    driver: bridge
