services:

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}  
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ###> symfony/mailer ###
  mailer:
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    container_name: mailer
    ports:
      - "25:25"
      - "587:587"  
    networks:
      - app-network
    restart: always

  ###> PHP ###
  php:
    build:
      context: ../back
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../back:/var/www/html
      - ./docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    depends_on:
      - database
      - mailer
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - DATABASE_URL=pgsql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - MAILER_DSN=smtp://mailer:1025
    restart: always

  ###> Server Nginx ###
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:443"
    volumes:
      - ./nginx/back/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../back:/var/www/html
      - ../ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - app-network
    restart: always
  ###> Web ###
  web: 
    build: 
      context: ../web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/web/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../ssl:/etc/nginx/ssl
    networks:
      - app-network
    restart: always

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:
  node_modules:

networks:
  app-network:
    driver: bridge
